version: v1
DBConfig:
  Dialect: postgres
  Host: 127.0.0.1
  Port: 1234
  Username: postgres
  Password: lucasthebear
  Name: launchpad
  Charset: utf8
GoogleRedirectUrl: "http://localhost:8080/v1/auth/google/callback"
