version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
      - image: circleci/golang:1.12
    environment:
      IMAGE_NAME: docker.pkg.github.com/getlaunchpad/server/launchpad
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: # restores saved cache if no changes are detected since last run
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$GITHUB_PASSWORD" | docker login docker.pkg.github.com -u "$GITHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Unit Test
          command: go test -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload:
          file: coverage.txt
          flags: backend,unittest
      - run:
          name: Deploy Code
          command: ./scripts/ci-deploy.sh
      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
